### ISSUE TITLE
RestSharp version

### ISSUE THREAD

**Issue by robsondealmeida** [topas/dotLastFm#1]
Hello,

First of all, thanks for the awesome lib. Well coded and a big time saving ... :relaxed: 

But, it doesn't work with the latest RestSharp version.
I have to install the RestSharp 102.7 to make dotLastFm work.

There's any reason for it?
Can it be upgraded to the latest version? If yes, maybe I can do the work ... :yum:

**Comment by topas** [comment]
Hi, 

Thanks! I am glad I helped!

And sorry for a little delay. :) dotLastFm should definitely work with the latest version of RestSharp. If it does not, it is wrong. It will be great if you can fix it.

**Comment by robsondealmeida** [comment]
Hello @topas ,
When I try to open the solution some projects did not load.

There's a problem with StyleCop

```
C:\dotLastFm\src\dotLastFm\dotLastFm.csproj : error  : The imported project "C:\Program Files (x86)\MSBuild\StyleCop\v4.6\StyleCop.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\dotLastFm\src\dotLastFm\dotLastFm.csproj

C:\dotLastFm\src\Tests\dotLastFm.IntegrationTests\dotLastFm.IntegrationTests.csproj : error  : The imported project "C:\Program Files (x86)\MSBuild\StyleCop\v4.6\StyleCop.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\dotLastFm\src\Tests\dotLastFm.IntegrationTests\dotLastFm.IntegrationTests.csproj

C:\dotLastFm\src\Tests\dotLastFm.IntegrationTests\dotLastFm.IntegrationTests.csproj : error  : The imported project "C:\Program Files (x86)\MSBuild\StyleCop\v4.6\StyleCop.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\dotLastFm\src\Tests\dotLastFm.IntegrationTests\dotLastFm.IntegrationTests.csproj

C:\dotLastFm\src\dotLastFm\dotLastFm.csproj : error  : The imported project "C:\Program Files (x86)\MSBuild\StyleCop\v4.6\StyleCop.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\dotLastFm\src\dotLastFm\dotLastFm.csproj
```

Can you put the settings.stylecop file(s) in the repo too?

Thanks.

**Comment by topas** [comment]
Hi, 
You have to install StyleCop to your computer. The error is about missing MsBuild target for StyleCop. And current version is 4.7 but dotLastFm is using 4.6, so I updated csproj files, updated psake version and some other things...

And now I am checking the problem with ReshSharp version. It seems like some issue with version specific versioning. I hope I will fix it and commit soon.

Thanks for your patience.

**Comment by topas** [comment]
Hi @robsondealmeida again, 

I just pushed the new version to nuget.org repository. Can you, please, update packages in your project? I am not sure if I fixed the reference issue right. 

Thanks.

**Comment by topas** [comment]
Hi @robsondealmeida, have you tried it? Can I close this issue? 

Thanks.
