### ISSUE TITLE
Artist.GetInfo()

### ISSUE THREAD

**Issue by DukeNuken** [topas/dotLastFm#2]
http://www.last.fm/api/show/artist.getInfo
1) It dont have way use mbid and other fields.
2) When I search by name which not english it doesnt work!

For example this one work in api
http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=Зимавсегда&api_key=5f033ca9655d417047d20d0d02fba1c4

var artistInfo = api.Artist.GetInfo("Зимавсегда"); //not found

even if do this 
                string NameEncoded = HttpUtility.UrlEncode(artist.Name);
                var artistInfo = api.Artist.GetInfo(NameEncoded);

Error:
Last.fm API Error (6):     The artist you supplied could not be found

**Comment by topas** [comment]
Hi @DukeNuken :) 

Thank you for the bug report. I found issue with empty <published/> element inside <bio>. I will commit the fix and also NuGet package.
