### ISSUE TITLE
Artist.GetInfo doesnt return mbid

### ISSUE THREAD

**Issue by DukeNuken** [topas/dotLastFm#3]
When I try to get artist.getinfo() for name "Dave Matthews & Tim Reynolds" api show fine result.

http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=Dave+Matthews+&+Tim+Reynolds&api_key=5f033ca9655d417047d20d0d02fba1c4

but the library doesnt return mbid for some reson
var artistInfo = api.Artist.GetInfo("Dave Matthews & Tim Reynolds");

problem with => artistInfo.MbId = "" 

can you check it please?

**Comment by topas** [comment]
Hi, 

thank you for your feedback! But is seems right. :)

You have to encode parameters in URL. Your example returns artist name "Dave Matthews" and output contains mbid element. 

This is url from dotLastFm - all parameters are encoded (inside RestSharp using HttpUtility.UrlEncode) and it get artist "Dave Matthews & Tim Reynolds". But output from last.fm does not contain mbid element. 
http://ws.audioscrobbler.com/2.0?method=artist.getInfo&artist=Dave%20Matthews%20%26%20Tim%20Reynolds&autocorrect=0&api_key=5f033ca9655d417047d20d0d02fba1c4

According to last.fm API documentation mbid is optional. http://www.last.fm/api/show/artist.getInfo
